### ISSUE TITLE
There is no control over the Error Alert.

### ISSUE THREAD

**Issue by thedp** [litoarias/HACLocationManager#3]

**Comment by litoarias** [comment]
Have you tried with a real device? I had the same error as you, but after upgrading to iOS 8.3, all sorted. Try it and I comets. A greeting!

**Comment by thedp** [comment]
Maybe I should have explained what I've meant.
It works OK, but the actual alert message displayed, when need; I can't control it's message.

P.S: We've decided not to use this controller due to it's license.

**Comment by litoarias** [comment]
what is the problem? Has MIT liecense

**Comment by thedp** [comment]
It says GPL https://github.com/litoarias/HACLocationManager/blob/master/LICENSE

**Comment by litoarias** [comment]
I'm sorry, was a mistake. Already modified for use! Enjoy!

**Comment by litoarias** [comment]
I'm sorry, was a mistake. Already modified for use! 
If you know how to fix the error, I would like to contribute.
Enjoy!
